### PR TITLE
Replace QTKit

### PR DESCRIPTION
**Pull request by Noreaster76**
[QTKit was replaced with AVFoundation](https://developer.apple.com/library/mac/technotes/tn2300/_index.html). This pull request upgrades from the former to the latter. It seems to have resolved a memory leak and subsequent crash in the process. I used to be able to only run the program for a few minutes before the program would crash and my entire machine would automatically restart, and after these changes, it no longer seems to do so.

Unfortunately, in making these changes, I kind of ripped out the functionality for saving images in formats other than JPEG. It can always be put back in later, I guess.

Other stuff included in this PR:
- Add a `.gitignore` file.
- Update deployment target to OS X Yosemite.
- Update to latest Objective-C syntax.
- Move C code into its own `main.m` file.
- Add Objective-Clean stylesheet to enforce a style guide.
- Use properties instead of instance variables.
- Remove superfluous comments.
- Rename properties.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@rharder any chance of getting this pull request merged? There's some talk of removing `imagesnap` from Homebrew since it cannot build with >= Xcode 8 but that would be a shame since we've had 340 installs in the last 30 days alone.

Cf. https://github.com/Homebrew/homebrew-core/pull/18837

**Comment by Noreaster76** [comment]
@ilovezfs I haven't noticed any activity from that account ( @rharder ) within the past few years with respect to this repo. If it's allowed by Homebrew, going forward, you may want to consider using a fork of this repo instead (and not just on a patch basis).

**Comment by ilovezfs** [comment]
@Noreaster76 the general rule in Homebrew is that it's allowed if the original upstream endorses the fork or if the fork adopts a separate project name and meets the notability requirements in its own right.

**Comment by ilovezfs** [comment]
@Noreaster76 in terms of alternative ways of contacting @rharder with your patch I see

http://kontactr.com/user/rharder
and
https://sourceforge.net/p/iharder/bugs

**Comment by rharder** [comment]
Sorry - not sure how I missed previous comments, but I see there's a merge request ready to go.  I just merged it, but I haven't gotten in to mess with imagesnap in a while.  Not sure about it building, but I know I use an old build of the binary, and that still works great as of summer 2017.

Not familiar with homebrew (I use ports).  How can I help get this integrated?

-Rob

**Comment by ilovezfs** [comment]
@rharder thank you for merging! The best way would be to create a new release tag here https://github.com/rharder/imagesnap/releases

**Pull request merged**
