### PR TITLE
Fix for macOS Catalina requiring permission or die

### PR DESCRIPTION
**Pull request by samwize**
Need to add camera usage info

### CODE REVIEW

**Comment by volmer** [comment]
Hey @samwize thanks for the PR. Is there a way for me to try this on my machine?

**Comment by rhuss** [comment]
@rharder any change to get this merged and having a new release ? That would be awesome !

I would help, but I'm not in macOS development that deep and would take me bit.

**Comment by rharder** [comment]
I have not gotten back to this or done the research to figure out what it would take to fix. -Rob

**Comment by rharder** [comment]
I'm working on getting an info.plist embedded in the binary.  Thanks for bringing it up.

**Pull request closed without merging**
